import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import TheHeader from "@/components/TheHeader";
import TheFooter from "@/components/TheFooter";

const inter = Roboto({ subsets: ["latin"], weight: ["700"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className + " layout_wrapper"}>
				<TheHeader />
				<main className="main">{children}</main>
				<TheFooter />
			</body>
		</html>
	);
}
